### ISSUE TITLE
Also external scripts

### ISSUE THREAD

**Issue by bakkot** [mikewest/inline-integrity#8]
First, sorry for dropping this thread earlier. I am very enthusiastic about this proposal!

Second, [I want to suggest](https://github.com/WICG/signature-based-sri/issues/10#issuecomment-2592273418) that this be made to work for external scripts as well. Right now use of signature-based SRI requires that the server responsible for the script add additional headers, which is often infeasible (e.g. if you're loading the script from a CDN).

This does require updating the `signature` attribute on the script at the same time as the script contents are updated, but in many deployments that's fine (e.g. because script URLs are versioned, so you're also updating the URL).

Concretely, this would allow you to update any script without needing to update the CSP, as long as you control the script tag itself and are capable of generating a signature for the script contents using a key recognized by the CSP. Right now, between this proposal and the original signature-based SRI, you can update any script _except_ for external scripts which are loaded from a server which doesn't sere the extra headers; such scripts still require you to use hashes (which is often not feasible; even leaving aside the issue of keeping them up to date, hashes disable `unsafe-inline`, which is still required in many deployments).

**Comment by mikewest** [comment]
This seems like a pretty reasonable request, offering a way of allowing developers to serve a CSP that contained the signing keys of their dependencies while relying on those dependencies to inject scripts asserting those keys and signatures across dynamic content.

I have a few thoughts:

* It doesn't seem to me to replace one of the central benefits of the approach which relies on HTTP Message Signatures, insofar as it requires the signature to be updated every time the page is updated. That makes sense for the deployment scenarios you're highlighting, but is less helpful for cases in which there's less direct interaction between the page's author and the script's author. In those cases an approach which allows pages to assert a key and resources to assert a signature seems more appropriate. We'd probably want both mechanisms, depending on the way a page is constructed.

* With that in mind, I suppose we'll need to define behavior for scenarios in which a signature is asserted both by the resource itself and by the inline attributes. Probably we'd verify both?

* We'd need to specify what the inline signature would sign. I'm assuming you'd suggest we sign the decoded response, just as we do when comparing a response to a digest in SRI? There's some risk of confusion there, given that the message signature version is much more flexible in the set of response components it can validate. We could try to jam some of that into the HTML attributes, but I suspect it would end up being more complicated than helpful to do so.

**Comment by bakkot** [comment]
> We'd probably want both mechanisms, depending on the way a page is constructed.

Yup, agreed.

> I suppose we'll need to define behavior for scenarios in which a signature is asserted both by the resource itself and by the inline attributes. Probably we'd verify both?

I actually think that if an inline `signature` is present, only it should be checked. The use case for inline signatures on external scripts is when you don't control the headers sent from the server, like with a CDN. If the CDN is adding the RFC 9421 headers for its own reasons, and if they're enforced even when an inline `signature` is present, then the page is forced to add the CDN's public key to the set of allowed keys in the CSP - which if they use that for every script is essentially equivalent to adding a host-source for the CDN, thus potentially considerably weakening the CSP. It also means that a previously valid page can be broken by its CDN adding valid RFC 9421 headers, which seems silly.

Also, if I've understood correctly, the CDN might not be including the integrity digest in the set of components which it signs in the `Signature-Input`, which would be rejected by the current signature-based SRI.

Since an inline `signature` implies that the contents of the response are known to the page, I don't think that you actually lose any security by ignoring the headers in this case.

One way to make this more clear would be to not use a separate `signature` attribute for inline signatures (for either inline or external scripts), and instead have a combined key+signature in the `integrity`. So `integrity="ed25519-keykeykey"` would mean that the server is expected to provide the signature, and `integrity="ed25519-keykeykey:sigsigsig"` would mean that `sigsigsig` is providing the signature.

A public key plus a signature over the contents is precisely equivalent to a hash of the contents except that it can only be generated using the private key, so it seems pretty natural if you're moving from a hash-source. This also removes the (very minor) problem of having to correlate `signature` values with keys in the integrity attribute in the case that there are multiple such.

>  I'm assuming you'd suggest we sign the decoded response, just as we do when comparing a response to a digest in SRI?

Yup. I agree there's some potential for confusion but I don't think it's that bad.

I don't really understand why the existing signature-based SRI has all the complexity with signing random other components except that it allows using an existing RFC; I don't see any reason to try to support that complexity here and I don't think developers are ever really going to think about the other components which RFC 9421 supports unless they're also configuring the server to manually send these headers, which is very unusual.

**Comment by mikewest** [comment]
> > I suppose we'll need to define behavior for scenarios in which a signature is asserted both by the resource itself and by the inline attributes. Probably we'd verify both?
> 
> I actually think that if an inline `signature` is present, only it should be checked. The use case for inline signatures on external scripts is when you don't control the headers sent from the server, like with a CDN.

I'm thinking about things in two stages:

1.  The server makes some assertions in the form of an `unencoded-digest` header and message signature headers. We should validate those assertions in all circumstances, and reject the resource if it's malformed.

2.  The page makes some assertions. Today those take the form of assertions about the key material expected for a given resource, and we can enforce them by simply comparing the expected key to the set of keys asserted by the resource. If there's a match, then we can simply rely on the enforcement in 1, and happily proceed.

    If we implemented the mechanism we're discussing here, the page's assertions could also take the form of an arbitrary key and signature. We wouldn't compare that key against the list of asserted signatures the server delivered. We'd instead perform validation directly.

So, we'd end up verifying both any signature asserted by the page, and any signature asserted by the resource. That seems fine to me, and I don't think it leads to the conflict you suggest below:

> If the CDN is adding the RFC 9421 headers for its own reasons, and if they're enforced even when an inline `signature` is present, then the page is forced to add the CDN's public key to the set of allowed keys in the CSP

The signatures provided by the resource only need to include a key required by the requesting page; that is `<script integrity="key1">` will accept a resource signed with key1, key2, key3, key8743, and key21 (though the browser will verify all of a resource's asserted signatures).

If we add inline signatures to the mix, they'd simply be a different check, rather than requiring a match with the delivered resource signatures.

> Also, if I've understood correctly, the CDN might not be including the integrity digest in the set of components which it signs in the `Signature-Input`, which would be rejected by the current signature-based SRI.

If the server asserts a signature of type `ed25519-integrity` that doesn't sign over the `Unencoded-Digest` header, then yes, it will be rejected. But because it will be consistently rejected, such a mistake would be quickly discovered and remedied.
 
> One way to make this more clear would be to not use a separate `signature` attribute for inline signatures (for either inline or external scripts), and instead have a combined key+signature in the `integrity`. So `integrity="ed25519-keykeykey"` would mean that the server is expected to provide the signature, and `integrity="ed25519-keykeykey:sigsigsig"` would mean that `sigsigsig` is providing the signature.

That could make sense. I don't have a super-strong opinion about the spelling (other than to note that SRI reserved `?` as a separator between the integrity metadata and any options provided). It made more sense to me to separate the signature into a distinct attribute, but jamming it onto the key is certainly not crazy.

@mozfreddyb might have opinions as SRI's editor, but tying the two together is probably reasonable.
 
> > I'm assuming you'd suggest we sign the decoded response, just as we do when comparing a response to a digest in SRI?
> 
> Yup. I agree there's some potential for confusion but I don't think it's that bad.

I think I agree.

> I don't really understand why the existing signature-based SRI has all the complexity with signing random other components except that it allows using an existing RFC; I don't see any reason to try to support that complexity here and I don't think developers are ever really going to think about the other components which RFC 9421 supports unless they're also configuring the server to manually send these headers, which is very unusual.

You've mentioned. :)

In short, folks have all sorts of reasons for wanting to sign things beyond the content. Asserting expirations to mitigate rollback attacks, signing bits like `content-type` or security headers to prevent replaying signed content in unexpected circumstances, and so on. I agree that the RFC introduces complexity, but my hope is that the existing tooling around that standard will make it simpler for developers to land in a reasonable place.

**Comment by simon-friedberger** [comment]
I don't really understand how a hardcoded signature is different from a hash. The hash is an input to the signature so it's not like you get any of the deployment benefits of using signatures.

**Comment by bakkot** [comment]
The benefit is that you can put the public key for the signature in the CSP and then update the script tag without having to update the CSP, whereas with a hash you have to update the CSP whenever it changes. Since the script tag and the CSP header are usually managed by completely different teams and in some cases completely different layers of the stack, that's a large benefit.

**Comment by simon-friedberger** [comment]
I agree with the general idea that supporting external scripts may be useful. I am just not sure I understand the overlap with different proposals.

So, to look at it in a different way, you want SRI with integrity="sha384-..." but instead of specifying the hash you specify the signature and key because it lets you also assert the right key in the CSP, correct?

I'm still not sure I see how this improves security compared to just specifying the hash in the tag. Are you assuming that the attacker could insert a new script tag with a valid integrity attribute? Can they also insert a new tag without an integrity attribute? Could you also achieve your goals by using an SRI hash and an Integrity-Policy header?

**Comment by bakkot** [comment]
> I'm still not sure I see how this improves security compared to just specifying the hash in the tag.

It doesn't, in itself; as you say, its security properties are pretty much identical. What it does is makes CSP easier to use, because now you don't need to update the CSP header every time the hash of a script changes. The fact that you have to do this currently is (in my experience) a significant bar to adopting hash-based CSPs; consequently people just stick with host sources so they don't have to do that.

> Could you also achieve your goals by using an SRI hash and an Integrity-Policy header?

No - my goal is to be able to use CSP to prevent script injection attacks, without using host sources (which have bad security properties, and also don't work if you use `strict-dynamic`) but also without using nonces or hash sources (which are operationally impossible in many deployments - nonces require updating the contents of the page on every load, hashes require changing the CSP header whenever a script changes).
